apiVersion: v1
kind: Service
metadata:
  name: sales-ui-service
  namespace: sales-test-ns
  labels:
    app: sales-ui 
spec:
  type: clusterIP
  selector:
    app: sales-ui-microservice
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP